= Fabio Oliveira

:showtitle!:
:address: Situlistraße 65  • 80538 • München • Germany
:phone: +49 174 304 11 68
:email: fabio.braga@gmail.com
:linkedin: http://br.linkedin.com/in/fabiobragaoliveira
:xing: https://www.xing.com/profile/Fabio_Oliveira9

_{address}_ +
[cols=".<20,.<80",frame=none,grid=none,width=100%,stripes=none]
|===
a|+Contacts+
a|
Mobile: {phone} +
Email: {email} +
Linkedin: {linkedin} +
XING: {xing} +


a|+Experience+
a|### IT Consulting/Solution Architect
Digital Loop GmbH +
Munich, DE +
Feb 2019 - current

* IT Consulting/Solution Architect on a contract basis, some past projects:
** Siemens: An ETL job implemented using Pentaho Data Integration (Kettle) and visualization using Tableau Desktop, a PoC for a larger deployment worldwide.
** Design Offices: Setup and management of the corporate website upgrade project using the Scrum methodology. Setup and Automation of a disaster recovery strategy using Google Cloud technologies and a CICD pipeline. Setup of the support process, monitoring and alert mechanisms to improve website availability.
** AutoScout24: Development of Frontend/Backend application using technologies as ReactJS, Typescript, Scala, Apache Kafka and AWS cloud. Development of data pipeline processes moving data from the AWS data lake and on-premisse databases to Salesforce Marketing Cloud following GDPR directives.


### Solution Architect
BMW AG +
Munich, DE +
Dec 2017 - Jan 2019

* Solution architect of the autonomous driving car project.
* Responsible for steering multiple projects and departments to achieve common goals and deadlines.
* Interface and communication boundaries definitions, designing security in the architecture, for data at rest and in transit.
* Definition of non-functional requirements on a realtime, IoT-like project, collecting data from vehicle sensors, feeding a data warehouse for posterior analisis and at the same time the fleet back with critical data like traffic jams, slippery roads, traffic signs or car accidents, using for such MQTT, Kafka, Redis cache and Kinesis queues. System designed to process Terabytes of data per month, many tens of thousands of messages per second.
* Modeling and best practices for a high available architecture in the cloud, using Multi Availability Zones and Multi Regions setup, with a active-active failover based on health metrics.
* Technically coaching teams on cloud technologies and infrastructure automation to adopt a cloud native architecture, using Terraform and Packer in a CICD pipeline for a fully automated deployment.
* Ramping up/Coaching new internal teams, helping them, POs and stakeholders on adopting agile methodologies.
* Requirements/User stories definitions for external contracts.


### Software Architect
Wirecard AG +
Munich, DE +
Mar 2016 - Dec 2017

* Responsible to design solutions and implement them, together with the team, using Java and the Spring Framework, and some others JVM based languages like Groovy and Scala.
* Focus on agility and increased business value, with a strong emphasis in test automation.
* Responsible to automate end-to-end business processes and software processes, applying Continuous Integration and Delivery, Infrastructure as Code, automating whetever possible to speedup the time to market while avoiding errors, using tools as Ansible and Puppet.
* Slicing a big legacy monolith in smaller microservices, while keeping backward compatility on a 24/7 system, using techniques like feature toggles, modularization and the strangler pattern.
* Participation on many internal and external events as a presenter, demonstrating technologies for other departments and divisions, or as a hiring strategy.
* Active member of the internal community, implementing Coding Dojo sessions, where in a safe environment developers could try, practice and learn new skills.
* Active participation on the hiring process, defining processes and applying them.

### Scrum Master & Software Engineer
Wirecard AG +
Munich, DE +
May 2014 - Mar 2016

* Responsible to help the team estimate, plan, design and implement new features required by the product owner, as a member of a Scrum team.
* Company main business on the finantial market, providing pre-paid cards technology infrastructure for its partners.
* Strongly multicultural environment.
* Working in the core module team using agile methodologies to delivery value to the company products.
* System with hard High Availability requirements. Using a private cloud, multiple nodes and a load
balance to not require planned downtime.
* As a Scrum Master my roles and responsibilities are: servant leadership, monitoring and tracking,
reporting and communication, process master, quality master, interface between team and product owner, resolve impediments, resolve conflicts, lead the scrum meetings, shield the team, team formation, estimation, performance appraisal & feedback and improvement management.

### Software Architect
CI&T +
Campinas, BR +
Nov 2012 - Mar 2014

* Responsible for the pre-sale analysis, design, project setup and deployment of a web application to manage the brazilian Walmart.com’s reverse logistic sector, controlling since the customer return of a product, the technical service sorting and estimation for fixing it, until the storage. The system is responsible for $6 million in products and generate a return of $100.000,00/month. The system uses Spring, Spring MVC, Hibernate and JPA 2 in the backend, and in the frontend HTML5, jQuery and BackboneJS.
* Responsible for the training of 30+ employees for 2 months about Java technologies, databases and good practices.

### Software Architect
CFlex BrainMerge +
Campinas, BR +
Nov 2010 - Nov 2012

* Responsible for the product customization (a Railroad mainline planner) for a australian client, one of the leaders in the production and refining of metals, the Rio Tinto Iron Ore. The system has a client-server architecture, written in Java Swing.
* Designed and implemented a Data Mining application to a national railway in Chile, the Empresa de Ferrocarrilles del Estado (EFE), to extract data about the train movements and infrastructure usage, and then, with this data, perform the processing of values owed by freight operators. This system is today responsible for all executives reports, outages predictions and billing.
* Designed and implemented a new network stack, departing from a stateful Apache Camel protocol to a lightweight and stateless REST-JSON stack, allowing the original system to scale from dozens to hundred of clients.

### Technical Leader
Símula +
Campinas, BR +
Sep 2007 - Nov 2010

* Designed and developed a web application to run into small devices used in forklifts using Google Web Toolkit, a server backend using JEE technologies and a administrative client using the NetBeans Rich Client Platform, to automate the storage and retrieval of products on the paper and cardboard industry, speeding the logistic and reducing the cost of storage.
* Responsible for the team training and the technical leadership during the main product migration from the legacy platform, in Object Pascal and using a 2-tier architecture, to a much more modern 3-tier architecture using the JEE platform.

### Technical Leader
CPqD +
Campinas, BR +
Jul 2005 - Sep 2007

* Technical leader in the CRM project for a energy supplier in Brazil, the CELG (Companhia Eletrica de Goias).
* The state of Goias has 6+ million habitants, the CRM needed to process the customers calls and claims, performing well for realtime attendance.
* Designed software solutions to scale for millions of database records
* System based on JEE technologies.

a|+Education+
a|### Project Management
Getúlio Vargas Foundation +
Campinas, BR +
Jan 2007 - Dec 2008

Classical project management course based on the PMBOK. Main subjects:

* Feasibility Analysis
* Enterprise Strategy
* Project Management Foundations
* Quality Management
* Acquisition Management
* Communication Management
* Cost Management
* Scope Management
* People Management
* Risk Management
* Time Management
* Conflict Management

### BSc in Computer Science
University of Sao Paulo +
Sao Paulo, BR +
Jan 1998 - Jun 2005

* Elective disciplines in Administration, Logic, Software Engineering and Artificial Intelligence
* Activities and groups: IME Junior Enterprise, Artificial Intelligence Group.

a|+Courses & Certificates+
a|### Amazon Web Services
* AWS Certified Solution Architect - Associate (in progress)

### Google Cloud Platform
* Certificates
** Google Cloud Certified Professional Cloud Architect

image:https://api.accredible.com/v1/frontend/credential_website_embed_image/badge/13274845[link="https://www.credential.net/rhu9np9o"]

> A Google Cloud Certified - Professional Cloud Architect enables organizations to leverage Google Cloud technologies. Through an understanding of cloud architecture and Google technology, this individual can design, develop, and manage robust, secure, scalable, highly available, and dynamic solutions to drive business objectives.

** Google Professional Data Engineer

image:https://api.accredible.com/v1/frontend/credential_website_embed_image/badge/13695794[link="https://www.credential.net/a2bnu44y"]

> A Professional Data Engineer enables data-driven decision making by collecting, transforming, and publishing data. A data engineer should be able to design build, operationalize, secure, and monitor data processing systems with a particular emphasis on security and compliance; scalability and efficiency; reliability and fidelity; and flexibility and portability. A data engineer should also be able to leverage, deploy, and continuously train pre-existing machine learning models.

* Courses:
** https://www.coursera.org/account/accomplishments/certificate/5PTS83H7YSHW[Building Resilient Streaming Systems on Google Cloud Platform]
** https://www.coursera.org/account/accomplishments/certificate/493UFFDASY9T[Serverless Machine Learning with Tensorflow on Google Cloud Platform]
** https://www.coursera.org/account/accomplishments/certificate/G6WG33ZLP5G2[Serverless Data Analysis with Google BigQuery and Cloud Dataflow]
** https://www.coursera.org/account/accomplishments/certificate/92B2B4SV85DM[Leveraging Unstructured Data with Cloud Dataproc on Google Cloud Platform]
** https://www.coursera.org/account/accomplishments/certificate/26ELRXMW83EB[Google Cloud Platform Big Data and Machine Learning Fundamentals]
** https://www.coursera.org/account/accomplishments/certificate/C277ZZHAQU9D[Essential Cloud Infrastructure: Core Services]
** https://www.coursera.org/account/accomplishments/certificate/KKU5UXCU6MQ5[Reliable Cloud Infrastructure: Design and Process]
** https://www.coursera.org/account/accomplishments/certificate/NZYLGKXDHJFH[Elastic Cloud Infrastructure: Scaling and Automation]
** https://www.coursera.org/account/accomplishments/certificate/DDH5ZSRKFA5A[Essential Cloud Infrastructure: Foundation]
** https://www.coursera.org/account/accomplishments/certificate/YRJCHCSRSZQY[Google Cloud Platform Fundamentals: Core Infrastructure]
** https://www.coursera.org/account/accomplishments/certificate/NZYLGKXDHJFH[Elastic Cloud Infrastructure: Containers and Services]

* Specializations
** https://www.coursera.org/account/accomplishments/specialization/QZF7RFY6YULA[Data Engineering, Big Data, and Machine Learning on GCP]
** https://www.coursera.org/account/accomplishments/specialization/PEV8RR69BZAX[Architecting with Google Cloud Platform]

### Scala
* Courses
** https://www.coursera.org/account/accomplishments/certificate/WRY8U5NKAQGW[Functional Programming in Scala Capstone]
** https://www.coursera.org/account/accomplishments/certificate/7YCF8HWU3SNW[Big Data Analysis with Scala and Spark]
** https://www.coursera.org/account/accomplishments/certificate/YVN779GEMT7P[Parallel Programming]
** https://www.coursera.org/account/accomplishments/certificate/6FUWRWRCDECN[Functional Program Design in Scala]
** https://www.coursera.org/account/accomplishments/certificate/DYD5AA2BRCRA[Functional Programming Principles in Scala]

* Specializations
** https://www.coursera.org/account/accomplishments/specialization/VM2U9XPSMX2Q[Functional Programming in Scala]

### Machine Learning
* https://www.coursera.org/account/accomplishments/certificate/VBD4H7UA57[Introduction to Recommendation Systems]

### University of Campinas
* Introduction to Natural Computing
* Bio-Inspired Algorithms

a|+Technical skills+
a|Click in the following button to see my stack in StackShare: image:https://img.shields.io/badge/tech-stack-0690fa.svg?style=flat[link="https://stackshare.io/fbdo/mytechstack"]

Summary:

Computer languages:: Java, Backend Javascript (NodeJS), Groovy, Python, Scala, Smalltalk

Protocols & APIs:: JEE full and micro profiles, Spring & Spring Boot, JMS, MQTT

Web Frameworks & RIAs:: Spring MVC, Google Web Toolkit, Vaadin

Databases:: Oracle, MySQL, PostgreSQL, Microsoft SQL Server

Infrastructure Automation:: Puppet, Ansible, Terraform, CloudFormation

Cloud Computing & Big Data:: Kafka, Hadoop, Sparks, Google Cloud Platform, Amazon Web Services, Microsoft Azure

a|+Awards+
a|NetBeans Innovators Grant 2008
MONOH project: http://plugins.netbeans.org/plugin/11670/monoh
Speech Recognizer for Netbeans Actions

a|+Languages+
a|
* Portuguese(native)
* English(advanced)
* Spanish(advanced)
* German(intermediate)
|===